### ISSUE TITLE
Support wildcard checks of multiple password files

### ISSUE THREAD

**Issue by bexelbie** [alzeih/pass-pwned#3]
Please add multiple file checks, for example `pass pwned d*` could check and report all pass files starting with a d

**Comment by alzeih** [comment]
As a workaround for right now, you might try:

`pushd ~/.password-store; find . -iname "*.gpg" | while read; do pass pwned "$(dirname $REPLY)/$(basename $REPLY .gpg)"; done; popd`

**Comment by bexelbie** [comment]
I did something similar in a less sophisticated bash for loop.  Do you think this should be documented as an idea, or do you think extending this with a multi-pass option like pass-update has is a good plan?

**Comment by alzeih** [comment]
Yeah, I think checking if multiple, or all, passwords are known to hibp is a reasonable thing to want to do. I’ll think about how this might work, and thanks for pointing out pass-update here.

**Comment by alzeih** [comment]
Okay, globbing is now supported with f289ebf11bc0d87383042f212cc1097707be1136.
