### ISSUE TITLE
Have Releases

### ISSUE THREAD

**Issue by bexelbie** [alzeih/pass-pwned#4]
I am working on packaging this for Fedora to make it more widely/easily available.  It would be nice if we could have releases so that release-monitoring.org could monitor for Fedora and other distributions.

Are you open to this idea?

**Comment by alzeih** [comment]
Sure! 

Give me a few days to clear my backlog, and then read up on release-monitoring.org, and to remind myself how to sign git tags, and see if I need anything else in the repository for packaging. 

I believe the minimum you may need for packaging is a git tag of the form "v0.0.0" with some kind of semantic versioning. Is this true? 

Is there anything else that would be useful to have?

**Comment by bexelbie** [comment]
I think that is all I need.  Would you like me to store the spec file here as well so others can adapt it for use with other RPM distributions?

**Comment by alzeih** [comment]
Okay, v0.1.0 is released https://github.com/alzeih/pass-pwned/releases/tag/v0.1.0 .

I decided not to use signed git tags for now.

If you would like to make a PR for the packaging bits then I'd be happy to take a look at it.
